//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiaoHangne.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class heheEntities : DbContext
    {
        public heheEntities()
            : base("name=heheEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaoCaoCongNo> BaoCaoCongNoes { get; set; }
        public DbSet<CapNhatDanhSachNhanVien> CapNhatDanhSachNhanViens { get; set; }
        public DbSet<DanhSachNhapHang> DanhSachNhapHangs { get; set; }
        public DbSet<DanhSachXuatHang> DanhSachXuatHangs { get; set; }
        public DbSet<DonHang> DonHangs { get; set; }
        public DbSet<KhachHang> KhachHangs { get; set; }
        public DbSet<LapDanhSachXe> LapDanhSachXes { get; set; }
        public DbSet<LichSuDonHang> LichSuDonHangs { get; set; }
        public DbSet<MaUuDai> MaUuDais { get; set; }
        public DbSet<NhanVien> NhanViens { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<ThongKeDoanhThu> ThongKeDoanhThus { get; set; }
        public DbSet<ThongKeThuNhap> ThongKeThuNhaps { get; set; }
    }
}
